@startuml
'https://plantuml.com/sequence-diagram

autonumber

group Взаимодействие с картинками
    Клиент -> API_Gateway: Запрос на сохранение/получение
    alt
    API_Gateway -> API_Gateway: Проверка доступа к ресурсу на основе JWT
    API_Gateway -> Data_Provider: Переадресация в сервис Data Provider
    alt
    Data_Provider -> Object_Storage: Запрос к Object Storage
    Object_Storage -->> Data_Provider: Ответ от хранилища
    Data_Provider -->> Клиент: Успешный ответ
    else Ошибка обработки запроса
    Data_Provider -->> Клиент:  Ответ с ошибкой
    end
    else Невалидный токен или отсутствует доступ к ресурсу
    API_Gateway -->> Клиент: Ответ с ошибкой
    end
end

legend right
|= Участник |= Описание |
| Клиент | Мобильное приложение пользователя |
| API_Gateway | Центральная точка входа, проверяет доступ по JWT |
| Data_Provider | Сервис для работы с данными |
| Object_Storage | Внешнее хранилище фотографий |
endlegend
@enduml